name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - name: Get pub packages
        run: flutter pub get
      # - run: flutter analyze .
      - name: Build APK
        run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ./build/release
  release-android:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: release-apk
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: (android) Release ${{ github.run_number }}
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./build/release
          asset_name: release-apk-${{ github.run_number }}.zip
          asset_content_type: application/zip
